#values for green.bag
hsvMin:  
  HMin : 70
  SMin : 70
  VMin : 0

hsvMax: 
  HMax : 110
  SMax : 255
  VMax : 255

verbose: true
loc_error: 0.2

height:
  hover: 5
  land : 1
  step : 0.4

delay:
  hover: 5
  transition: 2

names:
  A: magnus
  B: spedix
  C: f450

mav_name: magnus

camera : 
  translation : [0, 0, 0]
  rotation : [0, -1, 0, -1, 0, 0, 0, 0, -1]